### ISSUE TITLE
How to use? 

### ISSUE THREAD

**Issue by abdhass** [lukasztecza/fxBot#44]
Hey any chance of the readme? Or is this still WIP
Would love to try it out and possibly contribute

**Comment by lukasztecza** [comment]
Hey, it is still in progress as it does not work as expected yet. However I will try to write some readme this or next weekend if you would like to try it.

**Comment by lukasztecza** [comment]
readme is now available

**Comment by abdhass** [comment]
Thanks! Will try it out this week. I see even though some simulation worked, your not getting good results on the live account.

OANDA's documentation mention how the practice account can be different than the live account. Il see if I can implement those differences
